version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies
      - mvn install
  build:
    commands:
      - echo Build started
      - mvn clean package

artifacts:
  files:
    - target/*.jar
cache:
  paths:
    - ~/.m2/**/*   # speeds up Maven builds